export function exportMarkdown(result, name) {
  const date = new Date().toISOString().split('T')[0]
  const lines = []

  lines.push(`# Incident Report: ${name || 'Untitled'}`)
  lines.push('')
  if (result.severityScore) {
    lines.push(`**Severity:** ${result.severityScore}/10${result.severityReason ? ` — ${result.severityReason}` : ''}`)
  }
  lines.push(`**Date:** ${date}`)
  lines.push('')

  lines.push('## Summary')
  lines.push(result.summary || '')
  lines.push('')

  if (result.timeline?.length) {
    lines.push('## Timeline')
    lines.push('| Time | Event |')
    lines.push('|------|-------|')
    for (const { time, event } of result.timeline) {
      lines.push(`| ${time} | ${event} |`)
    }
    lines.push('')
  }

  if (result.hypotheses?.length) {
    lines.push('## Hypotheses')
    result.hypotheses.forEach((h, i) => {
      lines.push(`### ${i + 1}. ${h.title} [${h.strength}]`)
      lines.push(h.explanation || '')
      if (h.evidence?.length) {
        lines.push('')
        lines.push('**Evidence:**')
        for (const ev of h.evidence) lines.push(`- \`${ev}\``)
      }
      lines.push('')
    })
  }

  if (result.fixSteps?.length) {
    lines.push('## Remediation Steps')
    result.fixSteps.forEach((step, i) => lines.push(`${i + 1}. ${step}`))
    lines.push('')
  }

  lines.push('---')
  lines.push('*Generated by [NERVE](https://nerve-ql1v.onrender.com)*')

  const md = lines.join('\n')
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${(name || 'incident-report').toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50)}.md`
  a.click()
  URL.revokeObjectURL(url)
}
